[package]
name = "nuun"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
prost = { version = "0.13.5", features = ["derive"] }
tokio = { version = "1.44.0", features = ["full"] }
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
